/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Controladores.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhoan Sebastián
 */
public class GUI_CrearUsuario extends javax.swing.JFrame {
    ControladorOperador controladorOperador;
    ControladorGerente controladorGerente;

    /**
     * Creates new form GUI_CrearUsuario
     */
    public GUI_CrearUsuario() {
        initComponents();
        controladorOperador = new ControladorOperador();
        controladorGerente = new ControladorGerente();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        crearUsuario = new javax.swing.JButton();
        primerNom = new javax.swing.JTextField();
        primerNombreLabel = new javax.swing.JLabel();
        segundoNombreLabel = new javax.swing.JLabel();
        segundoNom = new javax.swing.JTextField();
        primerNombreLabel1 = new javax.swing.JLabel();
        primerAp = new javax.swing.JTextField();
        primerNombreLabel2 = new javax.swing.JLabel();
        segundoAp = new javax.swing.JTextField();
        primerNombreLabel3 = new javax.swing.JLabel();
        ced = new javax.swing.JTextField();
        primerNombreLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        primerNombreLabel5 = new javax.swing.JLabel();
        primerNombreLabel6 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        primerNombreLabel7 = new javax.swing.JLabel();
        cel = new javax.swing.JTextField();
        primerNombreLabel8 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        primerNombreLabel9 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        primerNombreLabel10 = new javax.swing.JLabel();
        confirmarpass = new javax.swing.JPasswordField();
        primerNombreLabel11 = new javax.swing.JLabel();
        preguntaSeguridad = new javax.swing.JTextField();
        primerNombreLabel12 = new javax.swing.JLabel();
        respuestaSeguridad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        crearUsuario.setText("CrearUsuario");
        crearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(crearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));
        getContentPane().add(primerNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        primerNombreLabel.setText("Primer Nombre:");
        getContentPane().add(primerNombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, -1));

        segundoNombreLabel.setText("Segundo Nombre:");
        getContentPane().add(segundoNombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));
        getContentPane().add(segundoNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 90, -1));

        primerNombreLabel1.setText("PrimerApellido:");
        getContentPane().add(primerNombreLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));
        getContentPane().add(primerAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, -1));

        primerNombreLabel2.setText("Segundo Apellido:");
        getContentPane().add(primerNombreLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 90, -1));
        getContentPane().add(segundoAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 90, -1));

        primerNombreLabel3.setText("Cedula");
        getContentPane().add(primerNombreLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 90, -1));
        getContentPane().add(ced, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 90, -1));

        primerNombreLabel4.setText("Tipo de Usuario:");
        getContentPane().add(primerNombreLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, -1));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 90, -1));

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operador", "Gerente", " " }));
        getContentPane().add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 100, -1));

        primerNombreLabel5.setText("Fecha de Nacimiento:");
        getContentPane().add(primerNombreLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, -1));

        primerNombreLabel6.setText("Telefono:");
        getContentPane().add(primerNombreLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 90, -1));

        tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telActionPerformed(evt);
            }
        });
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 90, -1));

        primerNombreLabel7.setText("Celular:");
        getContentPane().add(primerNombreLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 90, -1));
        getContentPane().add(cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 90, -1));

        primerNombreLabel8.setText("Email:");
        getContentPane().add(primerNombreLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 90, -1));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 90, -1));

        primerNombreLabel9.setText("Contraseña:");
        getContentPane().add(primerNombreLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 90, -1));

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 110, -1));

        primerNombreLabel10.setText("Confirmar:");
        getContentPane().add(primerNombreLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, -1));

        confirmarpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarpassActionPerformed(evt);
            }
        });
        getContentPane().add(confirmarpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 110, -1));

        primerNombreLabel11.setText("Pregunta:");
        getContentPane().add(primerNombreLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 90, -1));
        getContentPane().add(preguntaSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 90, -1));

        primerNombreLabel12.setText("Respuesta:");
        getContentPane().add(primerNombreLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 90, -1));
        getContentPane().add(respuestaSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioActionPerformed
        // TODO add your handling code here:
        String primerNombre, segundoNombre, primerApellido, segundoApellido,
               cedula, tipoUsuario, fechaNacimiento, telefono, celular, email, contrasena,
               confirmar, pregunta, respuesta;
        
       primerNombre = primerNom.getText();
       segundoNombre = segundoNom.getText();
        primerApellido = primerAp.getText();
        segundoApellido = segundoAp.getText();
        cedula = ced.getText();
        tipoUsuario = (String) tipo.getSelectedItem();
        fechaNacimiento = fecha.getText();
        telefono = tel.getText();
        celular = cel.getText();
        email = correo.getText();
        contrasena = pass.getText();
        confirmar = confirmarpass.getText();
        pregunta = preguntaSeguridad.getText();
        respuesta = respuestaSeguridad.getText();
        
       tipoUsuario = "Operador";
       if (tipoUsuario.equals("Operador")){
            int numFilas = controladorOperador.insertarOperador(primerNombre, 
               segundoNombre, primerApellido, segundoApellido,
               cedula, fechaNacimiento, telefono, celular, email, 
               contrasena, confirmar, pregunta, respuesta);
            
            
        
        System.out.println ("Filas "+ numFilas);
        if (numFilas == 1){
            JOptionPane.showMessageDialog(null, "Operador creado exitosamente");
        }
        else if (numFilas == 5){
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }
        else {
            JOptionPane.showMessageDialog(null, "Ocurrio un problema al guardar el Programa");
        }
       }
       else if (tipoUsuario.equals("Gerente")){
           
       }    
    }//GEN-LAST:event_crearUsuarioActionPerformed

    private void telActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void confirmarpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_CrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_CrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ced;
    private javax.swing.JTextField cel;
    private javax.swing.JPasswordField confirmarpass;
    private javax.swing.JTextField correo;
    private javax.swing.JButton crearUsuario;
    private javax.swing.JTextField fecha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField preguntaSeguridad;
    private javax.swing.JTextField primerAp;
    private javax.swing.JTextField primerNom;
    private javax.swing.JLabel primerNombreLabel;
    private javax.swing.JLabel primerNombreLabel1;
    private javax.swing.JLabel primerNombreLabel10;
    private javax.swing.JLabel primerNombreLabel11;
    private javax.swing.JLabel primerNombreLabel12;
    private javax.swing.JLabel primerNombreLabel2;
    private javax.swing.JLabel primerNombreLabel3;
    private javax.swing.JLabel primerNombreLabel4;
    private javax.swing.JLabel primerNombreLabel5;
    private javax.swing.JLabel primerNombreLabel6;
    private javax.swing.JLabel primerNombreLabel7;
    private javax.swing.JLabel primerNombreLabel8;
    private javax.swing.JLabel primerNombreLabel9;
    private javax.swing.JTextField respuestaSeguridad;
    private javax.swing.JTextField segundoAp;
    private javax.swing.JTextField segundoNom;
    private javax.swing.JLabel segundoNombreLabel;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
